- name: Remove HashiCorp yum repo (not supported on RHEL 9)
  ansible.builtin.file:
    path: /etc/yum.repos.d/hashicorp.repo
    state: absent

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - unzip
      - curl
    state: present

- name: Download Vault binary
  ansible.builtin.get_url:
    url: https://releases.hashicorp.com/vault/1.15.6/vault_1.15.6_linux_amd64.zip
    dest: /tmp/vault.zip
    mode: '0644'

- name: Unzip Vault binary
  ansible.builtin.unarchive:
    src: /tmp/vault.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'

- name: Create Vault config directory
  ansible.builtin.file:
    path: /etc/vault.d
    state: directory
    mode: '0755'

- name: Copy vault config file
  ansible.builtin.template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl
    mode: '0644'

- name: Create vault systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/vault.service
    mode: '0644'
    content: |
      [Unit]
      Description=HashiCorp Vault
      After=network-online.target
      Wants=network-online.target

      [Service]
      ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reexec

- name: Start Vault service
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: yes
